name: macOS Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flet

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Flet Build macOS
      working-directory: ./app
      run: |
        flutter config --no-analytics
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        which flet
        flet --version
        flet build macos --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      continue-on-error: true

    - name: Check build output
      #working-directory: ./app
      run: |
        echo "Contents of current directory after build:"
        ls -la
        echo "Contents of build directory (if it exists):"
        ls -la build || echo "build directory does not exist"
        echo "Contents of build/macos directory (if it exists):"
        ls -la build/macos || echo "build/macos directory does not exist"

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: macos-build-artifact
        path: /build/macos/**/*
        if-no-files-found: warn
        overwrite: false
    - name: Debug - List build directory
      run: |
        ls -R /build
